use_frameworks!

target 'WebView-Utilities_Example' do
  pod 'WebView-Utilities', :path => '../'

  target 'WebView-Utilities_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
