use_frameworks!

target 'WebView-Utilities_Example' do
  pod 'WebView-Utilities', :path => '../'

  target 'WebView-Utilities_Tests' do
    pod 'WebView-Utilities', :path => '../'

    pod 'Quick', '~> 0.8'
    pod 'Nimble', '~> 3.0'
  end
end
